name: Auto Blog Poster

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Runs every day at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Clean Puppeteer
        run: |
          rm -rf node_modules package-lock.json
          npm install puppeteer

      - name: Generate Blog Post
        run: node generatePost.js

      - name: Configure Git
        run: |
          git config --global user.name "Dinesh Auto Bot"
          git config --global user.email "dineshbala1204@gmail.com"

      - name: Pull latest changes (avoid push conflict)
        run: git pull origin main --rebase --autostash

      - name: Commit & Push Changes
        run: |
          git add .
          git commit -m "🤖 Auto blog post for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin main
